version: '3'

services:
  postgres_db:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=ok
      - POSTGRES_DB=cashtracker_db
      - POSTGRES_DATABASE=cashtracker_db
    ports:
      - '5432:5432'
  web:
    container_name: cashtracker_app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - postgres_db
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://alex:ok@localhost:5432/cashtracker_db
      - DB_PORT=4000
      - DB_HOST=postgres_db
      - DB_USER=alex
      - DB_PASSWORD=ok
      - DB_NAME=cashtracker
      - DB_DIALECT=postgres
      - JWT_SECRET=playwithmyboops
      - FRONTED_URL=http://192.168.0.7:3000
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_PORT=2525
      - EMAIL_USER=b764f53942ebaa
      - EMAIL_PASS=92bcbf84f4eff5
    depends_on:
      - postgres_db # Service B depends on Service A